export const CREATE_PROFILE = "CREATE_PROFILE"
export const GET_USER_PROFILE = "GET_USER_PROFILE"
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"
export const CREATE_EDUCATION = "CREATE_EDUCATION"
export const CREATE_EXPERIENCE = "CREATE_EXPERIENCE"

// success
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS"
export const CREATE_EDUCATION_SUCCESS = "CREATE_EDUCATION_SUCCESS"
export const CREATE_EXPERIENCE_SUCCESS = "CREATE_EXPERIENCE_SUCCESS"

// failed
export const CREATE_PROFILE_FAILED = "CREATE_PROFILE_FAILED"
export const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED"
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED"
export const CREATE_EDUCATION_FAILED = "CREATE_EDUCATION_FAILED"
export const CREATE_EXPERIENCE_FAILED = "CREATE_EXPERIENCE_FAILED"

// user
export const USER_LOGIN = "USER_LOGIN"
export const USER_SIGNUP = "USER_SIGNUP"
export const USER_LOGOUT = "USER_LOGOUT"

// success types
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"

// failed types
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED"

// Loading
export const SET_LOADING = "SET_LOADING"

export const CANCEL_ALL_MESSAGES = "CANCEL_ALL_MESSAGES"


// 
export const TRY_AUTO_LOGIN = "TRY_AUTO_LOGIN"
export const TRY_AUTO_LOGIN_SUCCESS = "TRY_AUTO_LOGIN_SUCCESS"

export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE"
export const SEARCH_ID = "SEARCH_ID"